(lang dune 3.19)

(name solutions)

(package
 (name solutions)
 (depends (ocaml (>= 5.4)))
)

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
